// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvjclztsxdnzrurhcsky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2amNsenRzeGRuenJ1cmhjc2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDQ5NDIsImV4cCI6MjA2NDg4MDk0Mn0.q6LzoUjpoMaz2gWFAGRo_kMOIPj2WwRDwWjj8jBkXss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);